### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by heconkhongmap** [bitpredator/empiretown#198]
I still don't understand part 5 in the installation process hope someone can help me

**Comment by bitpredator** [comment]
Hi @heconkhongmap , to create the start.bat file go to the "server-data" folder you will have to right click the mouse and create a new file with the ".bat" extension instead of "txt" or something else. Then open the file you just created by right clicking and editing on it and enter the startup path for example:

**Comment by bitpredator** [comment]
Hi @heconkhongmap , from now on you can use the .bat file in the "server-data" folder to start the server.
Greetings :
